language: python

python:
    - "2.7"

before_install:
  - sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-en

install:
    - pip install -e . -r ./requirements-dev.txt

before_script:
    - mkdir ~/.ngipipeline && cp test_ngi_config.yaml ~/.ngipipeline/ngi_config.yaml

script:
    - pytest --cov=ngi_pipeline ngi_pipeline/tests/engines/

after_success:
  - codecov

notifications:
    email: false
